In [43]:
import numpy as np

In [ ]:
# part1_1_1: Create a 1D NumPy array with integers from 10 to 20 (inclusive).

In [44]:
part1_1_1 = np.array([10,11,12,13,14,15,16,17,18,19,20])

In [45]:
print(part1_1_1)

[10 11 12 13 14 15 16 17 18 19 20]


In [67]:
# part1_1_2: Create a 2D NumPy array with shape (3, 4) filled with random integers between 1 and 50.

In [68]:
part1_1_2 = np.empty((3,4),dtype=int)

In [69]:
x = 0

In [70]:
y = 0

In [71]:
while x < 3:
    part1_1_2[x, y] = np.random.randint(1, 51)
    y += 1
    if y == 4:
        y = 0
        x += 1

In [72]:
print(part1_1_2)

[[22 11 39 36]
 [50 18 38 48]
 [22 32  4  4]]


In [73]:
# part1_1_3: Create a 3x3 identity matrix using NumPy.

In [74]:
part1_1_3 = np.eye(3, dtype=int)

In [75]:
print(part1_1_3)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [76]:
# part1_2_1: Extract the second row from the 2D array created above.

In [77]:
part1_2_1 = print(part1_1_2[1, 0:4])

[50 18 38 48]


In [78]:
# part1_2_2: Access the element in the 3rd row and 2nd column.

In [79]:
part1_2_2 = print(part1_1_2[2, 1])

32


In [80]:
# part1_2_3: Extract the last element of the first row.

In [81]:
part1_2_3 = print(part1_1_2[0, 3])

36


In [82]:
# part1_3_1: Reshape a 1D array of 12 elements into a 3x4 matrix.

In [83]:
part1_3_1 = np.arange(12).reshape(3, 4)

In [84]:
print(part1_3_1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [85]:
# part1_3_2: Flatten a 2D array into a 1D array.

In [86]:
part1_3_2 = part1_3_1.reshape(-1)

In [87]:
print(part1_3_2)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [92]:
# part2_4 = Create two NumPy arrays: a = np.array([1, 2, 3, 4]) and b = np.array([5, 6, 7, 8]).

In [117]:
a = np.array([1, 2, 3, 4])

In [118]:
b = np.array([5, 6, 7, 8])

In [119]:
# part2_4_1: Add the two arrays element-wise.

In [120]:
part2_4_1 = np.empty(4, dtype = int)

In [121]:
x1 = 0

In [122]:
while x1 < 4:
    part2_4_1[x1] = a[x1] + b[x1]
    x1 += 1

In [129]:
print(part2_4_1)

[ 6  8 10 12]


In [138]:
# part2_4_2: Multiply the two arrays element-wise.

In [139]:
part2_4_2 = np.empty(4, dtype = int)

In [140]:
x2 = 0

In [141]:
while x2 < 4:
    part2_4_2[x2] = a[x2] * b[x2]
    x2 += 1

In [142]:
print(part2_4_2)

[ 5 12 21 32]


In [143]:
# part2_4_3: Find the dot product of the two arrays.

In [144]:
part2_4_3 = part2_4_2[0] + part2_4_2[1] + part2_4_2[2] + part2_4_2[3]

In [145]:
print(part2_4_3)

70


In [ ]:
# part2_5_1: Create an array c = np.array([0, np.pi/2, np.pi]). Use NumPy’s trigonometric functions to compute the sine, cosine, and tangent of each element in the array.

In [146]:
c = np.array([0, np.pi/2, np.pi])

In [147]:
x3 = 0

In [148]:
while x3 < 3:
    print(np.sin(c[x3]), np.cos(c[x3]), np.tan(c[x3]))
    x3 += 1

0.0 1.0 0.0
1.0 6.123233995736766e-17 1.633123935319537e+16
1.2246467991473532e-16 -1.0 -1.2246467991473532e-16


In [149]:
# part2_5_2: Create a 5x5 array of random values and use NumPy’s log function to compute the natural logarithm of each element. 

In [151]:
part2_5_2 = np.random.rand(5, 5)

In [152]:
print(np.log(part2_5_2))

[[-0.391981   -0.16228201 -0.02839452 -1.67201167 -2.78197598]
 [-0.74020801 -0.86151718 -0.35308221 -0.41691858 -0.91530654]
 [-0.41029629 -2.2738727  -2.30901158 -1.309844   -0.89262163]
 [-1.17670196 -0.0931857  -0.02558456 -1.07074849 -1.54832548]
 [-0.12590066 -4.83766113 -0.11244048 -0.12611401 -2.47882256]]


In [153]:
# part2_6_1: Generate a random 1D array with 100 elements using np.random.rand(100)

In [154]:
part2_6_1 = np.random.rand(100)

In [155]:
print(part2_6_1)

[0.6668989  0.213941   0.32624386 0.80129453 0.60399397 0.0967849
 0.96860215 0.15703352 0.35668856 0.95805862 0.84208744 0.44561181
 0.91777696 0.62643422 0.32307614 0.06307314 0.07665481 0.30337119
 0.6907298  0.07807513 0.43484093 0.84193172 0.06702652 0.40557398
 0.54979041 0.3199727  0.46883514 0.82553243 0.01401158 0.5213947
 0.14780004 0.37607044 0.31016492 0.53020744 0.98419433 0.65158703
 0.61613113 0.41019605 0.04224485 0.11399856 0.41810824 0.6793206
 0.43732663 0.16483251 0.69911847 0.44035481 0.30674745 0.8119227
 0.90434371 0.79550462 0.317293   0.23289995 0.57676742 0.40225984
 0.22628574 0.20151228 0.80123219 0.78151345 0.87569264 0.51850393
 0.26071706 0.04540467 0.63607515 0.52481632 0.1809858  0.01478244
 0.63231432 0.02250563 0.28870575 0.68124233 0.99575651 0.71396222
 0.28913917 0.12650787 0.69327325 0.30706344 0.32668379 0.4674855
 0.28218768 0.71248591 0.21423504 0.24054685 0.33995956 0.14598774
 0.84746751 0.5591024  0.84052861 0.62304991 0.52680375 0.91774312


In [ ]:
# part2_6_2_1 = Mean

In [157]:
print(np.mean(part2_6_1))

0.483578070298486


In [ ]:
# part2_6_2_2 = Median

In [158]:
print(np.median(part2_6_1))

0.4565486551320016


In [ ]:
# part2_6_2_3 = Standard deviation

In [159]:
print(np.std(part2_6_1))

0.27559373573245216


In [ ]:
# part2_6_2_4 = Sum

In [160]:
print(np.sum(part2_6_1))

48.3578070298486


In [196]:
# part3_7_1: Create a 3x3 array filled with random integers between 10 and 100.

In [197]:
part3_7_1 = np.random.randint(10, 101, (3,3))

In [198]:
print(part3_7_1)

[[11 92 20]
 [32 77 94]
 [61 41 64]]


In [199]:
# part3_7_2: Sort the array in descending order.

In [200]:
part3_7_2 = part3_7_1.reshape(1, 9)

In [201]:
part3_7_2 = np.sort(part3_7_2)[::-1]

In [202]:
part3_7_2 = part3_7_2.reshape(3,3)

In [203]:
print(part3_7_2)

[[11 20 32]
 [41 61 64]
 [77 92 94]]


In [ ]:
# part3_7_3: Find the maximum and minimum values in the array.

In [204]:
print(part3_7_2.max())

94


In [205]:
print(part3_7_2.min())

11


In [206]:
# part3_8_1: Create a 5x5 array of integers from 1 to 25.

In [207]:
part3_8_1 = np.random.randint(1, 26, (5,5))

In [208]:
print(part3_8_1)

[[ 6  7 25 10 24]
 [10  2 12 18 21]
 [11 14  2  8 18]
 [16  6 21 25 23]
 [12 15  5 17  9]]


In [210]:
# part3_8_2: Slice the middle 3x3 section of the array.

In [211]:
part3_8_2 = part3_8_1[1:4, 1:4]

In [212]:
print(part3_8_2)

[[ 2 12 18]
 [14  2  8]
 [ 6 21 25]]


In [213]:
# part3_8_3: Extract the last column of the array.

In [214]:
part3_8_3 = part3_8_1[:, -1]

In [215]:
print(part3_8_3)

[24 21 18 23  9]


In [219]:
# part3_8_4: Extract every second row and second column.

In [228]:
part3_8_4 = part3_8_1[1::2, 1::2]

In [229]:
print(part3_8_4)

[[ 2 18]
 [ 6 25]]
